cuttle-cards/cuttle

- LICENSE.md
Modeled after the latest MIT license, https://mit-license.org/.
> Add license.md, resolves #26

- config/env/production.js
This PR fixes a security flaw where sails [blueprint routes](https://sailsjs.com/documentation/concepts/blueprints) are exposed in production. Thankfully security policies on the user controller made this not as heinous as it could have been, but it facilitates cheating as well as scraping. For (horrifying) reference, check out: https://www.cuttle.cards/game
> fix: disable blueprint routes in production

- client/js/components/GameView/UsernameToolTip.vue
- client/js/views/GameView.vue
- tests/e2e/specs/in-game/layout.spec.js
This PR adds player usernames to the game view - the opponent's username should display below their score, and the player's username should display above their score.
**Test Steps**
* Add `.only` to the test statement added below in `layout.spec.js`
* Start cypress with `npm run e2e:gui`
* Select `layout.spec.js`
* When the test starts, you should see the two player usernames display
> Add player usernames to GameView

- client/js/views/GameView.vue
* Choose an action that will display the target overlay
* The target overlay should display as it did before without being pushed down
> Fixes target overlay border cutting through hand

- client/js/components/GameView/UsernameToolTip.vue
- client/js/views/GameView.vue
* Open up a game
* Hover over a username - the username's background should longer flash to a bigger size when you hover away
* The opponent's username should remain in the upper left corner as their hand changes size
> Fix username flashing on hover and opponent's username position

- client/js/components/GameView/Card.vue
- client/js/components/GameView/GameOverlays.vue
- client/js/views/GameView.vue
- tests/e2e/specs/in-game/oneOffs.spec.js
Verify the modified test passes and bask in the satisfaction of knowing when a card is frozen.
> Add visual indicator to frozen card

- client/js/views/Rules.vue
Just a minor typo fix (updated description of "Two - Effect 2" move to be more precise).
Closes #127
> Fix typo in 'Two - Effect 2' move description (closes #127)

- client/js/components/StatsLeaderboard.vue
- client/js/components/StatsLeaderboardCell.vue
- tests/e2e/specs/out-of-game/stats.spec.js
As requested in #182 , this adapts the "Players Beaten" dialog to include a list of **Losses** in addition to the list of **Wins**.
In the "Total" column, a counter is also shown next to the player's name, depicting the number of times each player appeared in winning/losing matches over the weeks.
All feedback is appreciated! :)
> Display players lost to in Stats Leaderboard

- client/js/views/GameView.vue
Adds class to fix card width when resolving seven. Fixes #179
> Add class to fix card width for resolving seven

- client/js/components/StatsLeaderboardCell.vue
- package.json
- tests/e2e/specs/out-of-game/stats.spec.js
Added `(X Won, X Lost, X Total)` text to the stats page, next to the win rate percentage. Updated tests accordingly.
> Add count of matches won, lost, and total to Stats page

- README.md
- package.json
Fixes #208 
This adds the `--inspect` flag to the `node app.js` command used by `start:dev` and `start:server`, to enable debugging the backend server by default.
With this, a section about debugging the backend server is added in README.md to inform people on debugging it using the node debugger in VSCode.
> Enable debugging the backend by default and update README.md

- package.json
- tests/e2e/specs/in-game/layout.spec.js
Changes include refactoring existing E2E tests and moving some 'Aesthetic tests', which are not necessarily have to be runned on the CI to `describe.skip('Aesthetic tests'` block to increase the CI performance 
Issue #192
> Move some assertion tests to skipped e2e tests block

- client/js/components/GameView/ReauthenticateDialog.vue
- package.json
Fixes #97 
As stated in the issue, this PR wraps `client\js\components\GameView\ReauthenticateDialog.vue`'s `v-text-field`s and buttons in a `form` element, with `@submit.prevent="login"`, following `LoginSignup` page's example.
> Add form element to ReauthenticateDialog.vue

- client/js/components/StatsLeaderboard.vue
- client/js/views/Stats.vue
- tests/e2e/fixtures/statsFixtures.js
- tests/e2e/specs/out-of-game/stats.spec.js
This is intended to facilitate creating a season page for the World Championship, where the leaderboard doesn't make sense or isn't necessary
> feat: hide the stats leaderboard when no matches are available

- src/components/GameView/GameCard.vue
- tests/e2e/specs/in-game/basicMoves.spec.js
- tests/e2e/specs/in-game/sevens.spec.js
This update fixes the tests and associated features for playing sevens, including the targeting overlay applied to targetable cards while selecting a target.
> Fix/sevens spec -- resolves #266

- tests/e2e/specs/in-game/reconnecting.spec.js
Resolves #265 
This fixes and unskips the tests in reconnecting.spec.js. The app logic was already in place; this only changes test code
> Fix/reconnecting resolves #265

- src/components/CreateGameDialog.vue
- src/components/GameView/CannotCounterDialog.vue
- src/components/GameView/CounterDialog.vue
- src/components/GameView/FourDialog.vue
- src/components/GameView/GameCard.vue
- src/components/GameView/GameDialogs.vue
- src/components/GameView/GameOverDialog.vue
- src/components/GameView/GameOverlays.vue
- src/components/GameView/MoveChoiceCard.vue
- src/components/GameView/MoveChoiceOverlay.vue
- src/components/GameView/OpponentRequestedStalemateDialog.vue
- src/components/GameView/ReauthenticateDialog.vue
- src/components/GameView/SevenDoubleJacksDialog.vue
- src/components/GameView/TargetSelectionOverlay.vue
- src/components/GameView/ThreeDialog.vue
- src/components/RulePreview.vue
- src/components/RulesDialog.vue
- src/views/GameView.vue
Resolves #289 by fixing all vue errors that were appearing in the frontend console. The broad strokes are:
1. Update dialogs to use `modelValue` prop instead of `value`
2. Removing v-ripple from a v-overlay
3. Ensuring components declare the events they emit
> Fix/console warnings - Resolves #289

- src/components/GameView/ReauthenticateDialog.vue
- src/components/Global/BaseSnackbar.vue
- src/views/GameView.vue
- src/views/HomeView.vue
- src/views/LoginView.vue
Little bit of both with this PR, fixed the mobile positioning and started the consolidation of the base components so we can reduce (and better use) the vuetify components.
> Convert snackbar to base component

- package-lock.json
- package.json
- src/components/GameView/GameDialogs.vue
I added a v-if statement based on the gameIsOver prop. This closes out the component before it has to run through all the computed values.
I tested this through the cypress GUI, as well as opening two browsers, making two users, and winning/losing/and stalemating, with network setting set to low end mobile.
> added v-if to game-over-dialog component

- package.json
- src/plugins/sails.js
- tests/e2e/specs/in-game/gameOver.spec.js
- tests/e2e/specs/in-game/spectating.spec.js
- tests/e2e/support/commands.js
- tests/e2e/support/helpers.js
Resolves #377 
Adds test case for spectating and seeing cannot counter dialog, then having dialog disappear and confirming that no overlay scrim is shown
> Fix bug where overlay scrim appeared while spectating after cannot counter dialog appeared/disappeared

- package.json
- src/views/LobbyView.vue
Fix bug where the lobby sounds wouldn't load in prod b/c they reference the /public folder which doesn't exist in prod
> fix: remove /public from lobby sounds urls

- api/controllers/game/spectate.js
- package-lock.json
- package.json
- tests/e2e/specs/in-game/spectating.spec.js
Relevant issue number (e.g. #404): #
This is a hot-fix for my displaying spectator usernames commit. If you left spectating a game, to return to watch it later you're name wouldn't be added back to the spectator list.
> Spectator display hotfix - Spectator names being displayed after leaving and returning

- .eslintrc.js
- src/components/GameListItem.vue
- src/components/Global/BaseDialog.vue
- src/components/Global/BaseSnackbar.vue
- src/components/StatsLeaderboard.vue
- src/store/modules/gameList.js
- src/views/StatsView.vue
Relevant issue number (e.g. #404): #340 
This PR adds the `semi` rule to the .eslintrc file, to enforce requiring a semicolon. Documentation regarding this rule can be found here: https://eslint.org/docs/latest/rules/semi.
I tested the new rule by removing the semicolons from the lines mentioned in the issue (lines 160 and 163 of [GameOverDialog.vue](https://github.com/cuttle-cards/cuttle/blob/6a73d2a7cb3cb624578f5dfbe7833c339b96a101/src/components/GameView/GameOverDialog.vue#L160)) as per below:
This resulted in the desired error messages when running `npm run lint`, as per below:
As a result of the new rule, several missing semicolons throughout the code were picked up:
I confirmed that these are corrected by running `npm run lint:fix`. I also confirmed all the tests …
> DevEx#340 Update linting to require semicolons

- package.json
- src/components/RulesDialog.vue
Fixes the only lint warning by breaking up a long line of text in the RulesView
Relevant issue number (e.g. #404): #
> chore: add line breaks to too-long text in rules

- docs/CONTRIBUTING.md
- package.json
Relevant issue number (e.g. #404): #
CONTRIBUTING.md
I change CONTRIBUTING.md in Make Changes section
We follow semantic versioning (semver) for Cuttle Cards, which uses version numbers like 4.3.22. The versioning scheme consists of major, minor, and patch versions. When submitting a PR, please update the version field in package.json based on the version label of the issue being addressed.
If the issue is labeled patch-version, increment the patch number in the version field (e.g., from 4.3.22 to 4.3.23).
If the issue is labeled minor-version, reset the patch number to zero and increment the minor version (e.g., from 4.3.22 to 4.4.0).
If the issue is labeled major-version, set both the patch and minor versions to zero and increment the major version (e.g., from 4.3.22 to 5.0.0).
Please …
> [documentation]: #422 Update CONTRIBUTING.md

- api/controllers/game/seven/untargeted-one-off.js
- package.json
- src/components/GameView/MoveChoiceOverlay.vue
- tests/e2e/specs/in-game/sevens.spec.js
Resolves #401 
- Fixed bug allowing one-off to be played on last card in deck
- Added logic to disable one-off option if deck is empty or if trying to play one off on last 7 in deck
- Added test cases for bug fix as well as disabling one off option
- Updated casing on error message of Fours to match casing on other errors
> Bug #401 Allowing one-off on itself if seven and last card in deck

- package.json
- src/components/GameView/CardListSortable.vue
Title: Fix Sorting Order Issue in Scrap Pile
Description:
This pull request addresses the sorting issue in the scrap pile, ensuring that cards appear in the correct order of scuttle priority. The problem was observed when sorting the scrap by rank, where the suit was ignored, leading to discrepancies from the expected order.
Problem:
Currently, the sorting logic only considers the rank of the cards, disregarding the suit. This resulted in cards being incorrectly ordered in the scrap pile, leading to an awkward display and inconsistent user experience.
Solution:
To resolve this, I have updated the CardListSortable component to sort the cards by both rank and suit. Now, the cards in the scrap pile will be sorted based on their rank, and in case of equal rank, they will be further sorted by …
> Fixed the sorting order

- package-lock.json
- package.json
- src/components/TheUserMenu.vue
- src/i18n.js
- src/main.js
- tests/e2e/specs/out-of-game/localization.spec.js
Resolves [[Feature]: Store language preference in local storage and set it when bootstrapping client #549](https://github.com/cuttle-cards/cuttle/issues/549)
> feat: using preferred language from local storage

- package-lock.json
- package.json
- src/components/TheFooter.vue
Relevant [issue number](https://github.com/cuttle-cards/cuttle/issues/583)
- Resolves #583 
- Has the documentation been updated accordingly: No need, minor UI change.
- Similar implementation used to set the color as is done in `TheHeader.vue`
- Can see result in image below
- **Note**: The primary color clashes a bit with the brown background in dark mode. For that, an option considered was to change the variant of the `v-btn` to `plain` instead of `text` to hide background. However, did not proceed with it since it also lowers the opacity of the text. More details [here](https://vuetifyjs.com/en/components/buttons/#variants).
> set the colors of the selected bottom nav elements to newPrimary

- package-lock.json
- package.json
- src/components/CreateGameDialog.vue
Relevant #614 
- Resolves #614 
I don't think additional details are required as it's just adding mr-2 (margin right: 8px)
> Added 8px margin between buttons in CreateGameDialog

- src/components/GameView/ReauthenticateDialog.vue
- src/components/GameView/ScrapDialog.vue
- Resolves #https://github.com/cuttle-cards/cuttle/issues/575
1: `scrollable` was not properly defined as a boolean in `src/components/GameView/ScrapDialog.vue`
2: `data-cy` was missing in `src/components/GameView/ReauthenticateDialog.vue`
> 575: Fix warnings

- src/routes/home/HomeView.vue
- src/routes/home/components/HowItWorksDialog.vue
#667 
There's a bit of overlap, but at least it now stays on one line
> Bug/667 French "How it works"-button spills to the next line

- src/routes/game/components/CannotCounterDialog.vue
- src/translations/en.json
- src/translations/es.json
- src/translations/fr.json
- tests/e2e/specs/in-game/one-offs/0_countering.spec.js
Resolves #626 
I have used google translator for the translations. Please review and suggest the changes.
Line number 19 -  `Your opponent has played ` will be now ` Your opponent has played the `. Since we already have a translation for line number 10, it felt redundant to have another translation just to skip `the`. Let me know if its really important not to have it. I can add new translation for that
> Cannot counter dialog translations

- config/policies.js
Resolves #688 
The policy had a camelCase and on starting server, there was a warning from middleware:
> [Bug] Fix case issue and middleware warning

- tests/e2e/specs/in-game/reconnecting.spec.js
- Resolves #694
Changed the `loadGameFixture` to load a non-winning hand
> Bug: #694 Reconnecting spec winning hand

- src/components/TheHeader.vue
- Resolves #581
For testing you can set the window width to 1000px and it should show you the navigation options in the header, at 960px it should show it as well but when lowered to 959px or less, the navigation options in header should be hidden and it should show the navigation footer
> (#581) navigation disappears between 960 & 1280px

- api/controllers/game/resolve-four.js
- api/services/gameService.js
- src/plugins/sockets/inGameEvents.js
- src/routes/game/GameView.vue
- src/routes/game/components/GameCard.vue
- src/stores/game.js
- Resolves #619 
- Updated API endpoint to added the discarded cards to the last event, as well as send the `cardsToScrap` in the socket message
- Added a state variable to the store `discardedCards`
- Dynamically showed suit and rank by checking if the cards id was inside `discardedCards`
- Added store function with timeout to delay store being updated.
- Added transition to flip card when changed
- The game will now only sort the players hand and not the opponents, this will also happen in the `updateGame` function in the store instead of in `populateGame` on the server side
https://github.com/cuttle-cards/cuttle/assets/108551827/430f4729-c9d9-4 …
> Feat #619 Animate fours

- src/plugins/sockets/inGameEvents.js
- src/stores/game.js
- Resolves #697 
- Removed unnecessary `resetState()` from socket call
- Set `myPNum` before `updateGame()` on `requestSubscribe()`
- Reordered and renamed `updateGameThanResetPNumIfNull()`
> Bug #697 Fix player hand sorting

- tests/e2e/specs/out-of-game/lobby.spec.js
> fix: update test references to ranked icon to use sword-cross

- api/controllers/game/set-is-ranked.js
- Resolves #705 
- The issue was caused by an unnecessary call to ``` gameStore.resetPNumIfNullThenUpdateGame(evData.game) ``` within the ``` inGameEvents.js ``` method when the ranked was updated. Since changing the game mode was not part of the ``` inGameEvent.js ```, an undefined value was passed, leading to the type error. Removed the call to the ``` game.publish ```  method to resolve the issue.
> fix: mode change type error

- src/routes/lobby/LobbyView.vue
- src/routes/lobby/components/LobbyPlayerIndicator.vue
- Resolves #723 
- Resolves #729  
A new animation is added for an opponent leaving the lobby, the animation is a pulse which goes well with the leave-lobby.mp3 available in the project sounds.
https://github.com/cuttle-cards/cuttle/assets/36615882/b979e113-e5e1-4666-b797-45eba0258b0c
This animation triggers for your opponent when it leaves the lobby and when you exit the lobby
<hr />
The other change, in LobbyPlayerIndicator fixes the wave animation and resolves #729. For testing, you can see how the animation react on three different breakpoints 540px - 1240px - 1920px.
> Feature #723 - Animate when players leaves the lobby

- src/routes/game/components/CannotCounterDialog.vue
- src/routes/game/components/ChooseWhetherToCounterDialog.vue
Restyles the counter and resolve buttons
- Resolves #767 
1. `CannotCounterDialog` now displays the a permanently disabled "Counter" button
2. The Counter button has been moved to the left and has been given the "newPrimary" pink color
Cannot Counter Dialog:
Counter Dialog:
> style: revise counter and resolve buttons

- src/routes/home/components/CreateGameDialog.vue
- Resolves #772
I added
```
class="d-flex align-center"
```
on the v-switch.  The same classes were already applied to the form parent element, but the v-switch has a container div that needs to be vertically align as well.
There might be a more 'vuetify-ish' way of handleing this ?
the v-swith component has a center-affix prop:
It's true by default, so I thaought it would be centering its content, but maybe I misunderstand this...
> flex and align-center classes added to the v-witch

- src/routes/game/components/GameOverDialog.vue
This changes the button color of the Rematch button in the `GameOverDialog` to the 'chocolate' surface-1
N/A
> style(GameOverDialog): change button color to surface-2

- src/routes/rules/RulesView.vue
This fixes a broken icon in the rules page
N/A
> fix(RulesView): replace mid-crown icon with mdi-crown

- src/stores/game.js
Prevents a null pointer exception where `this.handleGameResponse()` is undefined because the `function` keyword creates its own `this` scope
- Resolves #
> fix: prevent NPE by replacing 'function' with () =>

- .github/workflows/bump-version.yml
- .github/workflows/prepare-version-bump.yml
> Feature: Automatic release based on version bump

- src/routes/game/components/ReauthenticateDialog.vue
- tests/e2e/specs/in-game/reconnecting.spec.js
- Resolves #847 
- Changed initial v-model value to be a data variable set to an empty string
- Wrote corresponding test to check that reauthenticate dialog works
> Bug #847 Reauthenticate dialog username input

- api/controllers/game/rematch.js
- tests/e2e/specs/in-game/gameOver.spec.js
- Resolves #845 
- Added functions to make an array of all previous rematch games
- Got the count of all wins and stalemates (p0 is based off p0 of game 1 in the series)
- Added assertions to check for correct game names
> Feat #845 Auto-generate rematch game names with score

- src/translations/en.json
- src/translations/es.json
- src/translations/fr.json
A user who is working on creating a Russian translation of the application asked where "collapseMenu" is used and this revealed that the translation key is stale and should be removed.
It was previously used in the navigation side-sheet, but since this component was replaced w/ top + bottom navigation in #530 , the "collapseMenu" string is no longer needed
N/A
> chore: remove stale 'global.collapseMenu' key from all translation files

- api/controllers/UserController.js
- api/controllers/game/concede.js
- api/controllers/game/face-card.js
- api/controllers/game/jack.js
- api/controllers/game/pass.js
- api/controllers/game/points.js
- api/controllers/game/rematch.js
- api/controllers/game/resolve.js
- api/controllers/game/seven/face-card.js
- api/controllers/game/seven/jack.js
- api/controllers/game/seven/points.js
- api/controllers/game/stalemate.js
- src/plugins/sockets/connectivityEvents.js
- src/stores/auth.js
- tests/e2e/specs/in-game/reconnecting.spec.js
- tests/e2e/support/commands.js
- Resolves #877 
- Added logic to API endpoints to save the Full game at game over into a `lastEvent` variable
- Added logic to `mustReauthenticate` to pull from the `lastEvent.game` if game is over
- Added test to make sure refresh correctly recovers state through lastEvent
> Bug#877 Reconnecting after game over

- src/routes/stats/StatsView.vue
- tests/e2e/fixtures/statsFixtures.js
template
Relevant [#885 ](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- Resolves #885
after the changes the stats chart will only render if there are games played in the selected tournament
> added a conditional statement in statsUsageChart template for the issue #885

- src/routes/game/components/dialogs/components/ChooseWhetherToCounterDialog.vue
- Resolves #882
Created two t() functions to fix the display problem.
> chooseWeatherToCounter message split in two t() functions

- src/routes/rules/components/ScuttleSuitOrder.vue
Fixes incorrect use of `sm` breakpoint and replaces it with the intended `smAndDown`
- Resolves #
> fid(ScuttleSuitOrder): fix mobile breakpoint to be smAndDown

- src/routes/lobby/LobbyView.vue
Fixes bug where lobby would play 'leave' sound when the game starts (because the component unmounted). Now plays join sound when game starts and leave sound when exiting
- Resolves #906 
> fix(LobbyView): play join sound when game starts 

- src/routes/rules/RulesView.vue
Relevant 915(https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- Resolves #915
Go to the rules page, on a mobile vue, try scrolling the page and see that the nav bar scrolls so that the newly highlighted jump link is visible
>  programmatically scroll the top nav when highlighting its jump link

- src/router.js
- Resolves #871
Navigating to  `/game` or `/spectate` without a gameId will now show the game unavailable view
Navigating to the lobby without a gameId will give you a snackbar error
> Bug #871 /Game and /Spectate bring you to blank screen

- src/routes/rules/RulesView.vue
Resolves #1006
The problem fixed by preventing boolean type to be passed to parentModalId prop
> vue warning about `parentModalId` type

- api/helpers/lock-game.js
Follow up to remove the hack in #1014. Now that the database has been migrated to include the `gamestaterows` table via the following script, we can remove the conditional nature of the `.populate('gamestates')` call:
```
CREATE TABLE gamestaterow (
id SERIAL PRIMARY KEY,
"gameId" INTEGER NOT NULL REFERENCES game(id) ON DELETE CASCADE,
"playedBy" SMALLINT NOT NULL CHECK ("playedBy" IN (0, 1)),
"moveType" TEXT NOT NULL,
"playedCard" TEXT,
"targetCard" TEXT,
"discardedCards" TEXT[] DEFAULT ARRAY[]::TEXT[],
turn INTEGER NOT NULL,
phase SMALLINT NOT NULL CHECK (phase IN (1, 2, 3, 4, 5, 7)),
"p0Hand" TEXT[] NOT NULL,
"p1Hand" TEXT[] NOT NULL,
"p0Points" TEXT[] NOT NULL,
"p1Points" TEXT[] NOT NULL,
"p0FaceCards" TEXT[] NOT NULL,
"p1FaceCards" TEXT[] NOT NULL,
deck TEXT[] NOT NULL,
scrap TEXT[] …
```
> fix(lock-game): remove conditional populate of gamestates

- api/helpers/gamestate/moves/points/execute.js
The `points/execute` move was missing the `playedBy` attribute from the returned GameState
- Resolves #
> fix(moves/points/execute): set playedBy in returned result

- api/helpers/gamestate/moves/counter/validate.js
- api/helpers/gamestate/moves/face-card/validate.js
- api/helpers/gamestate/moves/one-off/validate.js
- api/helpers/gamestate/moves/points/validate.js
The `/validate.js` helpers had been copying the inconsistent variable name `cardPlayed` while the `GameState` and `GameStateRow` values actually used by the `execute()` and `saveGameState()` helpers use the name `playedCard` (as it's more consistent with `targetCard`. This PR renames all instances of `cardPlayed` to `playedCard` to match
No issue - small name change
> chore: rename cardPlayed to playedCard across validate() helpers

- api/helpers/gamestate/moves/draw/execute.js
- api/helpers/gamestate/moves/face-card/execute.js
- api/helpers/gamestate/moves/pass/execute.js
- api/helpers/gamestate/moves/points/execute.js
- api/helpers/gamestate/moves/seven-points/execute.js
Fixes bug where `playedCard` and `targetCard` would carry over between moves
- Resolves #1061 
> fix: set playedCard and targetCard to null when appropriate

- src/routes/game/components/GameMenu.vue
- src/translations/en.json
- src/translations/es.json
- src/translations/fr.json
- tests/e2e/specs/in-game/reconnecting.spec.js
- Resolves #945 
-Added refresh option in game menu and added translations
-Added corresponding test
> Feat #945 Add refresh to game menu

- .eslintrc.js
- package-lock.json
- package.json
- Resolves #[1131](https://github.com/cuttle-cards/cuttle/issues/1131)
Adds [package Eslint-Plugin-Mocha](https://www.npmjs.com/package/eslint-plugin-mocha) as a dependency. ~~Using recommended settings to apply linting to Cypress test.~~
**removed recommended settings due to too many failed linting requirements until further discussion**
Test Rule Changes:
~~Turned off test for no arrow functions been passed to cypress test.~~
Changed warn to error on .only() test.
> Dev ex 1131 configure eslint to error on .only()

- src/util/badWordsEn.js
- Resolves #1174
See [superset-remover](https://github.com/tcox-coding/superset-remover) for implementation details. All superset words have been removed, as well as the words `cox` and `butt`. The new list of words is down from 410 words to 217 words. Additionally, the document has been formatted alphabetically and commented.
Given this is just updating the profanity filter, I don't see much in the way of testing to validate the accuracy of this change.
> Feature Dedupe and Remove 'butt' from `badWordsEn.json`

- jsconfig.json
This adds `jsconfig.json` to the top level directory in order to let language servers know about the directory aliasing. Specifically, this helps vscode intellisense pick up on imports prefixed with `_` for top-level dir and `@` for `src`.
- Resolves #
> feat(jsonconfig.json): init file

- api/helpers/game-states/moves/scuttle/execute.js
- tests/e2e/specs/in-game/basicMoves.spec.js
Fixes bug where scuttling was not putting jacks into the scrap
- Resolves #
> fix(scuttle/execute): scrap all jacks when scuttling

- src/main.js
- src/plugins/rollbar.js
Users are reporting that navigating to the home page sometimes crashes the app with an out of memory error (Oh Snap! in chrome). Due to #1161 and issues with rollbar performance in the past, I'm disabling the error logger to see if that's the culprit.
- Resolves #
> fix: disable rollbar in the hopes that this prevents the home page crashes

- src/routes/lobby/LobbyView.vue
Relevant [#1199 ](https://github.com/cuttle-cards/cuttle/issues/1199)
- Resolves #1199 - color of switch changed to newPrimary
PFA the screenshot of the fix on the ranked/casual switch button
[
](url)
>  Fix for issue #1199-color of the ranked and casual switch changed to newPrimary

- src/routes/game/components/GameMenu.vue
Adds icons to the game menu for concede and stalemate
- Resolves #
> feat(GameMenu.vue): add icons for concede and request stalemate

- src/stores/game.js
- tests/e2e/specs/in-game/spectating/replays.spec.js
- tests/e2e/support/commands.js
Fixes bug where replays show an extra card disappearing when someone scuttles
- Resolves #
> fix(game.js): fix processScuttle()'s handling of cards not being found to check for indices === -1 instaed of undefined

- src/stores/game.js
Refactors the `game` store as a setup store to allow it to utilize composables e.g. `useRoute()`
N/A
> refactor(game.js): rewrite as setup store
