- .github/lint-build-test.yml
move lint outside cypress action and configure cypress action to use baseUrl http://localhost:1337
> fix: Reconfigure worklow 

- .github/workflows/lint-build-test.yml
- client/js/views/LoginSignup.vue
- tests/e2e/specs/out_of_game/authentication.spec.js
Does this get deployed if the checks fail?
> test: make first test fail and add text to login page

- CODE_OF_CONDUCT.md
Still need a valid email address or some other form of contact for this, but it's probably useful to have and would show up in the root of your repo.
- https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#supported-file-types
- https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project#adding-a-code-of-conduct-using-a-template
> Add code of conduct, resolves #24

- client/js/views/Rules.vue
> fix: update ace rule text

- client/js/views/LoginSignup.vue
Adds autocomplete for password managers to the main login/signup forms.
> Add autocomplete to input fields

- package.json
Small adjustment to remove double vue devtools from loading.
> Fix start:dev script

- client/js/components/GameView/GameDialogs.vue
- client/js/store/modules/game.js
- client/js/views/GameView.vue
- client/js/views/Lobby.vue
Breaking up GameView and pulling dialogs out in to their own component.
Trello mentioned also pulling out overlays, etc, but I feel like this is already big enough and that may need to be it's own ticket to reduce the cognitive load of even looking at this.
> Convert dialogs to separate component, breaking up GameView

- client/js/views/Stats.vue
> feat: open tournament links in a new tab

- client/js/components/GameView/CardListSortable.vue
- tests/e2e/specs/in-game/layout.spec.js
- tests/e2e/specs/in-game/oneOffs.spec.js
Not yet, but it's what i'll do next!
> feat:now sorts by rank by default

- client/js/components/GameView/GameOverlays.vue
- client/js/store/modules/game.js
- client/js/views/GameView.vue
> Move overlays to separate component

- client/js/plugins/sails.js
> fix: prevent request stalemate dialog when game ends

- config/policies.js
Made changes to policies config to fix correct route for game/reject-stalemate to game/stalemate-reject
> fix: Correct route for game/reject-stalemate policy config

- client/js/components/GameView/GameOverlays.vue
- client/js/components/GameView/MoveChoiceOverlay.vue
- tests/e2e/specs/in-game/oneOffs.spec.js
- [:white_check_mark: ] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle#run-the-tests))
- [:white_check_mark: ] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle#linting-formatting))
> Add frozen indicator to card overlay

- .eslintignore
- .eslintrc.js
- .github/workflows/deploy-storybook.yml
- .gitignore
- .storybook/main.js
- .storybook/manager.js
- .storybook/preview-head.html
- .storybook/preview.js
- .storybook/storybook.css
- .storybook/theme/cuttle/index.js
- .storybook/theme/cuttle/styles.css
- README.md
- client/js/plugins/vuetify.js
- package-lock.json
- package.json
- stories/Introduction.stories.mdx
- stories/components/AwardCard.stories.js
- stories/components/GameView/UsernameToolTip.stories.js
- Pull down this branch
- Run `npm ci`
- Run `npm run storybook`
- Rejoice 👏🏼 
- Add Vuetify to Storybook (maybe?)
- https://github.com/nidkil/vuetify-with-storybook
- https://www.c-od-e.com/2019/06/30/vuejs-vuetify-and-storybook-integration/
- https://github.com/desiboli/storybook-vue-vuetify
- Style global storybook theme
- Test github pages deployment
- Add/Update documentation
- Identify components that would make sense in Storybook
> [Feature] Add initial Storybook support

- .github/workflows/deploy-storybook.yml
> Bug: Adjust Storybook deployment directory

- api/controllers/game/concede.js
- api/controllers/game/create.js
- api/controllers/game/pass.js
- api/controllers/game/stalemate.js
- api/helpers/add-game-to-match.js
- api/hooks/customGameHook/index.js
- api/services/gameService.js
- client/js/components/CreateGameDialog.vue
- client/js/store/modules/gameList.js
- client/js/views/Home.vue
- tests/e2e/specs/in-game/gameOver.spec.js
- tests/e2e/specs/out-of-game/home.spec.js
- tests/e2e/specs/out-of-game/lobby.spec.js
- tests/e2e/support/commands.js
- tests/e2e/support/helpers.js
> fix: replace all references to 'ranked' with 'isRanked' to match db

- .github/workflows/pr-actions.yml
> [Feature]: Increase GitHub Action Timeout

- client/js/components/GameListItem.vue
- client/js/store/modules/game.js
- client/js/views/Lobby.vue
- tests/e2e/specs/out-of-game/lobby.spec.js
> [Feature]: Lobby should show whether a game is ranked, resolves #106

- client/js/views/Home.vue
- client/js/views/Rules.vue
This is a tiny enhancement that changes the way we access Vuex Store from direct to using `mapState` helper (closes #136)
> Enhancement: Use 'mapState' for accessing store games list from store (closes #136)

- tests/e2e/specs/in-game/reconnecting.spec.js
> test: skip all reconnection tests pending fix

- README.md
#144 **_I have added Contributor Images In readme.md file_**
> Contributor Added

- README.md
Discord link to Github Readme Added!, Please label my PR as hacktoberfest-accepted Thankyou!
> Discord link to Github Readme Added!

- api/services/cardService.js
- client/js/components/RulePreview.vue
- client/js/views/Rules.vue
- ~~[ ] Have tests been added to cover any new features or `fixes?~~
- ~~[ ] Has the documentation been updated accordingly?~~
* Removed "Preview" from the gif buttons on the rules page
* Capitalized Royals
* Removed unnecessary apostrophes
* `delete` -> `dealer`
* Sentences end with a period
* Replaced one `==` with a `===`
* Removed deprecated `frameborder`
* Added an FAQ about what happens if a 7 reveals two Jacks and your opponent has no points in play
* Added an FAQ about what happens if you 7 with one card left in the deck.
* Added note to the Draw option about passing.
> Updated rules page, tweaking the grammar and clarifying some things

- .github/ISSUE_TEMPLATE/DEV-EXPERIENCE.yml
Quick PR to add the DevEx issue template - should close https://github.com/cuttle-cards/cuttle/issues/154.
> add dev-experience github issue template

- client/js/components/CreateGameDialog.vue
- client/js/components/StatsScoringDialog.vue
- package.json
- tests/e2e/specs/out-of-game/home.spec.js
- tests/e2e/specs/out-of-game/lobby.spec.js
> 152: Shows ranked explanation on game creation

- package.json
> chore: bump package version to 3.2.2

- README.md
- client/js/views/GameView.vue
I made sure the history went to the newest message from issue #183. I also made sure it changed on page refresh.
I also added changed the wording on the read me to tell new developers that it needs node version 16.
> Completed Issue #183

- README.md
- docs/GAME_RULES.md
> feature/game-rules-md - #178 separated game rules from README.md

- client/js/components/GameView/CardListSortable.vue
> feat/three-dialog-size-fix #206

- client/js/views/GameView.vue
> Add css to fix issue with cards missing

- client/js/components/GameView/Card.vue
- client/js/views/GameView.vue
> Add CSS for card sizes

- client/js/components/GameView/CannotCounterDialog.vue
- client/js/components/GameView/CounterDialog.vue
- client/js/components/GameView/FourDialog.vue
- client/js/components/GameView/GameOverDialog.vue
- client/js/components/GameView/OpponentRequestedStalemateDialog.vue
- client/js/components/GameView/ReauthenticateDialog.vue
- client/js/components/GameView/ScrapDialog.vue
- client/js/components/GameView/SevenDoubleJacksDialog.vue
- client/js/components/GameView/ThreeDialog.vue
- package.json
> add css to fix size and space in dialog

- client/js/App.vue
- client/js/views/GameView.vue
- package.json
- tests/e2e/support/commands.js
Updates cypress to version 12.1.0, removes some `.then()` calls that were chained off of unchainable commands
> Fix/cypress 10+

- client/js/components/GameView/GameOverlays.vue
- client/js/components/GameView/MoveChoiceOverlay.vue
- package.json
- tests/e2e/specs/in-game/sevens.spec.js
> Add disable text for cards in hand when resolving a seven oneOff

- tests/e2e/specs/in-game/basicMoves.spec.js
- tests/e2e/specs/in-game/gameOver.spec.js
- tests/e2e/specs/in-game/layout.spec.js
- tests/e2e/specs/in-game/oneOffs.spec.js
- tests/e2e/specs/in-game/reconnecting.spec.js
- tests/e2e/specs/in-game/sevens.spec.js
- tests/e2e/specs/out-of-game/health.spec.js
- tests/e2e/specs/out-of-game/home.spec.js
- tests/e2e/specs/out-of-game/lobby.spec.js
- tests/e2e/specs/out-of-game/navigation.spec.js
- tests/e2e/specs/out-of-game/stats.spec.js
> Add '.skip' to failing in-game tests

- tests/e2e/specs/in-game/basicMoves.spec.js
> Fix broken 'Quadruple Jacks' test with a force click

- client/js/views/Home.vue
Adds event info + a call to action to join discord to the homepage
> feat: add info on event times to homepage

- src/components/GameView/GameMenu.vue
- src/components/GameView/MoveChoiceCard.vue
- src/components/GameView/MoveChoiceOverlay.vue
> Style/move choice overlay (Resolves #276)

- src/components/GameView/GameOverlays.vue
- src/components/GameView/MoveChoiceOverlay.vue
- src/components/StatsLeaderboard.vue
- src/views/HomeView.vue
- src/views/StatsView.vue
- tests/e2e/fixtures/statsFixtures.js
- tests/e2e/specs/in-game/sevens.spec.js
- tests/e2e/specs/out-of-game/stats.spec.js
> merge main into vue-3

- src/components/AwardCard.vue
- src/components/CreateGameDialog.vue
- src/components/StatsScoringDialog.vue
- tests/e2e/specs/out-of-game/home.spec.js
> Feat: Fix home spec tests, resolves #268

- tests/e2e/specs/out-of-game/lobby.spec.js
> [DevEx]: Fix failing lobby.spec test, fixes #269

- tests/e2e/specs/out-of-game/navigation.spec.js
> [DevEx]: Fix failing navigation.spec test, fixes #270

- tests/e2e/specs/in-game/layout.spec.js
> [DevEx]: Fix failing layout.spec test, fixes #263

- package.json
- src/router.js
- src/views/LoginView.vue
- tests/e2e/specs/out-of-game/authentication.spec.js
> chore: merge 3.4.2 in to feature/vue-3

- package-lock.json
- package.json
- src/components/AwardCard.vue
- src/components/StatsLeaderboard.vue
- src/components/StatsLeaderboardCell.vue
- src/views/StatsView.vue
- tests/e2e/specs/out-of-game/stats.spec.js
Fixes the features and tests that power the stats page. Resolves #271. Could still use a visual once-over
> Fix/stats page -- resolves #271

- src/views/GameView.vue
Resolves #304 by removing the drop shadow and background color from the deck
> Fix/deck style - Fixes #304

- src/components/GameView/ReauthenticateDialog.vue
- src/views/GameView.vue
- src/views/HomeView.vue
- src/views/LoginView.vue
Fixes #288 by applying correct styles (button type and flex layout) to snackbars
> Fix/snackbar styles - Fixes #288

- src/components/GameView/GameCard.vue
- src/views/GameView.vue
Fixes the transition classes and the image on the scuttling card
> Fix/scuttle animation - fixes #301

- src/components/StatsLeaderboardCell.vue
Resolves #312 by applying correct chip style (elevated or outlined)
> fix: apply correct chip variant

- package.json
- src/plugins/sails.js
- src/store/modules/auth.js
- tests/e2e/specs/in-game/socket.spec.js
- utils/config-utils.js
Fixes bug where random socket disconnects caused missing updates
> test: implement failing test case for recovering missing socket event

- package.json
- src/components/StatsLeaderboard.vue
- src/components/StatsLeaderboardCell.vue
- src/components/StatsScoringDialog.vue
- tests/e2e/fixtures/statsFixtures.js
- tests/e2e/specs/out-of-game/stats.spec.js
- [/] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle#run-the-tests))
- [/] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle#linting-formatting))
With this change, those who have one at least one match in a given week without placing will receive 2 points, and those with at least one match played but no wins will receive 1 point
**To Test:**
* In `tests/e2e/specs/out-of-game/stats.spec.js`, add `.only` to `it('Displays Headers, Cards, and Table')`
* Run the test
* _Player4_ should now have 1 point in week 2
* _Player5_ should now have 2 points in week 2
> [Feature]: Revise scoring system to 5, 4, 3, 2, 1 for each week

- api/controllers/game/concede.js
- api/controllers/game/pass.js
- api/controllers/game/stalemate.js
- api/helpers/add-game-to-match.js
- api/services/gameService.js
- package.json
- src/components/GameView/GameDialogs.vue
- src/components/GameView/GameOverDialog.vue
- src/store/modules/game.js
- tests/e2e/specs/in-game/gameOver.spec.js
> Feat/Game over rework - resolves #105

- api/policies/hasValidUsername.js
- package.json
- src/views/LobbyView.vue
In this issue, we have to remove the white space from the username. I run the project on localhost and test all the cases.
issue:   #362 
https://user-images.githubusercontent.com/89539376/232382697-fb69ba72-4dda-4d0f-92f9-62e4e27ba2bb.mp4
> Remove white space from username

- .github/PULL_REQUEST_TEMPLATE.md
Relevant issue number (e.g. #404): #404 
This is my first open source contribution, so I apologise if I went wrong anywhere along the way!
Added 'issue number' heading to the pr template file.
Also took the opportunity to update a few links in the pr template, as they appeared to be out of date.
> Devex #404: Updated pr template.

- api/controllers/TestController.js
- package-lock.json
- package.json
- src/router.js
- src/views/StatsView.vue
- tests/e2e/fixtures/statsFixtures.js
- tests/e2e/specs/out-of-game/navigation.spec.js
- tests/e2e/specs/out-of-game/stats.spec.js
- tests/e2e/support/commands.js
fixes #281 
Added test and logic to add url params to /stats page.  e.g /stats/4
> Feature #281 enable stats page link

- .eslintrc.js
- package.json
- src/components/CreateGameDialog.vue
- src/components/GameListItem.vue
- src/components/GameView/CannotCounterDialog.vue
- src/components/GameView/ChooseTwoDialog.vue
- src/components/GameView/ChooseWhetherToCounterDialog.vue
- src/components/GameView/GameCard.vue
- src/components/GameView/GameMenu.vue
- src/components/GameView/GameOverDialog.vue
- src/components/GameView/MoveChoiceOverlay.vue
- src/components/GameView/ScoreGoalToolTip.vue
- src/components/GameView/ScrapDialog.vue
- src/components/GameView/TargetSelectionOverlay.vue
- src/components/Global/BaseDialog.vue
- src/components/Global/BaseSnackbar.vue
- src/components/RulePreview.vue
- src/components/RulesDialog.vue
- src/components/StatsLeaderboardCell.vue
- src/components/StatsScoringDialog.vue
- src/views/GameView.vue
- src/views/HomeView.vue
- src/views/LobbyView.vue
- src/views/LoginView.vue
- src/views/RulesView.vue
- src/views/StatsView.vue
Relevant issue number : #415
With Reference to issue https://github.com/cuttle-cards/cuttle/issues/415,
Made a change for linting
> Fix linting, edit Linting rules. 

- api/controllers/UserController.js
- package-lock.json
- package.json
- src/components/GameView/GameUnavailableOverlay.vue
- src/components/GameView/GameUnavailableView.vue
- src/store/modules/game.js
- src/views/GameView.vue
- tests/e2e/specs/in-game/reconnecting.spec.js
Relevant issue number: Fixes #405 
- Added a Game unavailable overlay that matches waiting for game to start overlay
- Moved new overlay and reauthenticate dialog into a new Game-unavailable-view component.
- Wrote test for new overlay.
> Bug #405 blank background

- api/controllers/game/resolve.js
- api/controllers/game/targeted-one-off.js
- package.json
- tests/e2e/specs/in-game/oneOffs.spec.js
Relevant issue number (e.g. #404): #433 
- Cleaned, and updated player updates for frozen cards
- Wrote associated test
> Bug #433 resolving one offs clear frozen card

- .github/PULL_REQUEST_TEMPLATE.md
- package-lock.json
- package.json
Relevant issue number (e.g. #404): #
> Updated PR template to say resolves in front of the issue number

- package.json
- src/views/LoginView.vue
Resolves  #442
ninja edit: I didn't test these changes as they were simple string changes. Please let me know if there are further items I need to complete for this PR to go through :)
> Fix typos in LoginView.vue

- api/services/gameService.js
- package.json
Relevant issue number (e.g. #404): Resolves #111 
- Refactored .populateGame to use async await, clean up the way it read and fail fast on logic
- Refactored .tempGame to programmatically set key value pairs
> Feature #111 refactor populate game

- package.json
- tests/e2e/support/commands.js
**WIP: DO NOT MERGE** (opening PR to execute CI runs to test the bug)
Relevant issue number (e.g. #404): Resolves #453 
> Fix: Resolve 'Error Subscribing' flaky failures in CI tests

- package.json
- src/views/HomeView.vue
Relevant issue number (e.g. #404): Resolves #431 
> fix: stop requesting to leave games from the home page

- package-lock.json
- package.json
- tests/e2e/specs/in-game/socket.spec.js
- tests/e2e/specs/in-game/spectating.spec.js
- tests/e2e/specs/out-of-game/home.spec.js
- tests/e2e/specs/out-of-game/lobby.spec.js
- tests/e2e/support/commands.js
@Haviles04 sent this over, https://docs.cypress.io/guides/references/migration-guide.
Relevant issue number: Resolves #
> Feature: Upgrade to Cypress 12

- package-lock.json
- package.json
- src/components/CreateGameDialog.vue
- src/components/Global/BaseSnackbar.vue
- src/components/StatsScoringDialog.vue
> Feature: Update packages to latest versions

- package.json
- src/components/GameView/ScrapDialog.vue
> Fix Issue #473

- package-lock.json
- package.json
- src/components/GameView/ReauthenticateDialog.vue
- src/plugins/vuetify.js
- src/views/GameView.vue
- src/views/LoginView.vue
- src/views/StatsView.vue
Resolves #484 
- ✅ Successfully run the stats.spec.js test
- ✅  Is the code formatted properly ?
> Resolved 484

- package.json
- src/views/LoginView.vue
> Issue Resolves 499

- package.json
- src/components/GameView/GameMenu.vue
- src/components/GameView/SpectatorListMenu.vue
- Resolves #497 
- Updated colors in `SpectatorListMenu.vue`
- Updated font color and used bg-color prop in `GameMenu.vue`
> Feature #497 Apply new colors to spectator list menu

- api/controllers/game/subscribe.js
- package.json
> Bug# 535 Sails bug warning

- api/policies/hasValidUsername.js
- package-lock.json
- package.json
> 541 undefined username

- package.json
- src/components/GameView/SpectatorListMenu.vue
- Resolves #538 
- Updated color props in v-list item
> Bug #538 spectator list menu colors

- package.json
- src/components/GameView/GameOverDialog.vue
- tests/e2e/support/helpers.js
- Resolves #557 
Modified existing tests to do additional checks on game result icons
> Fix GameOverDialog game status icon and text, resolves #557

- package-lock.json
- package.json
- src/components/TheFooter.vue
- src/components/TheHeader.vue
- src/components/TheUserMenu.vue
- src/composables/navLink.js
- src/i18n.js
- tests/e2e/specs/out-of-game/localization.spec.js
> Feat: Enable Language Translation

- package-lock.json
- package.json
- src/components/Global/BaseDialog.vue
- src/components/StatsScoringDialog.vue
changed the background colour and text colour
- Resolves #511
changed persistent to false on baseDialogue.vue
added bg color and text color for the dialogue box as per the requirments
> Changed persistent to false and changed the colors as required

- package-lock.json
- package.json
- src/components/TheHeader.vue
Relevant [#560 ](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- Resolves #
- All tests ran successfully
- The code is formatted properly , according to the guidelines
- No tests added
- No documentation update
> Fix #560 Added 4px margin between icons and text

- package-lock.json
- package.json
- src/components/TheHeader.vue
#578 
- Resolves #578 
- [ Think so] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#run-the-tests))
- [✅ ] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#linting-formatting))
- [No ] Have tests been added to cover any new features or fixes?
- [ No] Has the documentation been updated accordingly?
> added desktop logo styles to src/components/TheHeader.vue

- docs/CONTRIBUTING.md
- package-lock.json
- package.json
Fixed a small grammatical mistake in the CONTRIBUTING.md file. Documentation change hence no linting/tests required.
Refer to the last sentence of the second paragraph of the "Commit your update" heading in CONTRIBUTING.md
> docs: fixed small grammatical mistake in CONTRIBUTING.md

- .github/workflows/bump-version.yml
Testing implementation of merging pr and automating version bump
- Resolves #
> feat: implement initial pass at major version bump action

- .github/workflows/bump-version.yml
work in progress  on version number automation
- Resolves #
> Push to `dev-temporary` on pr merge into `dev-tempoarary`

- .github/workflows/bump-version.yml
> Change step name to 'push please' just to run pr with label

- .github/workflows/bump-version.yml
> Configure git for pushing the version bump

- .github/workflows/bump-version.yml
> Setup minor and patch version bumps

- .github/workflows/bump-version.yml
> fix indentation

- .github/workflows/bump-version.yml
> fix checkout to fetch first

- .github/workflows/bump-version.yml
- package-lock.json
- package.json
> sort out merges from clean slate

- .github/workflows/bump-version.yml
- package-lock.json
- package.json
- src/components/LobbyPlayerIndicator.vue
- src/components/TheFooter.vue
- src/translations/en.json
- src/translations/es.json
- src/translations/fr.json
- src/views/LobbyView.vue
- tests/e2e/specs/out-of-game/localization.spec.js
> Try running version bump with branch protection

- package-lock.json
- package.json
- src/components/AwardCard.vue
- src/components/GameListItem.vue
- src/components/GameView/CannotCounterDialog.vue
- src/components/GameView/CardListSortable.vue
- src/components/GameView/ChooseWhetherToCounterDialog.vue
- src/components/GameView/GameCard.vue
- src/components/GameView/GameMenu.vue
- src/components/GameView/GameOverDialog.vue
- src/components/GameView/MoveChoiceCard.vue
- src/components/GameView/MoveChoiceOverlay.vue
- src/components/GameView/OpponentRequestedStalemateDialog.vue
- src/components/GameView/ScoreGoalToolTip.vue
- src/components/GameView/ScrapDialog.vue
- src/components/GameView/SpectatorListMenu.vue
- src/components/GameView/TargetSelectionOverlay.vue
- src/components/Global/BaseSnackbar.vue
- src/components/RulePreview.vue
- src/components/RulesDialog.vue
- src/components/StatsScoringDialog.vue
- src/views/GameView.vue
- src/views/LobbyView.vue
- src/views/LoginView.vue
- src/views/RulesView.vue
> Added aria attributes to all the icons

- .github/workflows/bump-version.yml
> feat: print secret comparison

- .github/workflows/bump-version.yml
> feat: add username to origin config

- package-lock.json
- package.json
- src/components/CreateGameDialog.vue
- src/components/GameListItem.vue
- src/translations/en.json
- src/translations/es.json
- src/translations/fr.json
- src/views/LobbyView.vue
> Fix: create game button translation

- package-lock.json
- package.json
- src/components/TheUserMenu.vue
> # 623 4px margin between icon and username

- .github/workflows/bump-version.yml
> set version bump to run on main-temporary

- .github/workflows/bump-version.yml
> Rerun version bump

- package-lock.json
- package.json
- Resolves #660 
https://docs.cypress.io/guides/references/migration-guide
> Upgrade Cypress to version 13, resolves #660

- src/components/GameView/GameMenu.vue
> Feat/ 637 Enable selecting your preferred language from the `GameMenu`

- src/routes/game/components/CardListSortable.vue
Relevant [#529](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- Resolves #529
> feat: cancel icon alignment updated in scrap list

- src/routes/game/components/CardListSortable.vue
- src/routes/game/components/ScrapDialog.vue
- src/translations/en.json
- src/translations/es.json
- src/translations/fr.json
Relevant [635](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- Resolves #635
> feat: applied translation to scrap dialog

- src/routes/game/components/FourDialog.vue
- src/translations/en.json
- src/translations/es.json
- src/translations/fr.json
> Feat/628 Apply translations/localization to all the text in the FourDialog

- src/routes/game/GameView.vue
- Resolves #689 
Changed transition time to 1s
> Bug #689 Flaky Threes Test

- .github/workflows/bump-version.yml
> feat(bump-version.yml): skip checkout if push token is missing

- src/routes/home/components/GameListItem.vue
- src/routes/lobby/LobbyView.vue
- Resolves  #706
-ranked games icon is now cross-sword
-refactor the v-icon with a dynamic icon prop to have only one instance
> Game icons

- tests/e2e/specs/in-game/one-offs/1_aces.spec.js
- tests/e2e/specs/in-game/one-offs/6_sixes.spec.js
- tests/e2e/support/commands.js
> Bug #471 setupGameAsP0 403

- package-lock.json
- package.json
> Update Cypress V13.4.0

- src/composables/themedLogo.js
> feat: set spooky logo for the month of october

- src/routes/game/components/CannotCounterDialog.vue
- src/routes/game/components/ChooseTwoDialog.vue
- src/routes/game/components/ChooseWhetherToCounterDialog.vue
- src/translations/en.json
- src/translations/es.json
- src/translations/fr.json
- tests/e2e/specs/in-game/one-offs/0_countering.spec.js
- tests/e2e/specs/in-game/reconnecting.spec.js
- Resolves #627 
-Combined `counterDialogs` with `cannotCounterDialogs`
-Added localization to Counter Dialogs
> Feat #627 Counter Dialog Localization

- src/stores/gameList.js
> fixed bug #745

- docs/CONTRIBUTING.md
- Resolves #757 
- [✅] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#run-the-tests))
- [✅] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#linting-formatting))
- [✅] Has the documentation been updated accordingly?
> added line 84 to CONTRIBUTING.MD

- src/routes/game/components/GameOverlays.vue
- Resolves #765
In GameOverlays.vue, I corrected the key pointing to the entry in the json language files.
> opponentConsideringStalemate displayed as text

- src/routes/game/GameView.vue
- src/stores/auth.js
- Resolves #794 
Added router check to `isSpectating` computed value in `GameView.vue` to check after reload
> Bug #794 Flaky spectate test

- src/translations/fr.json
* Some grammar fixes (verbs)
* Formal tone (no "tu", always "vous")
* No Title Case in French
* No space before punctuation, align with Canadian and Swiss styles
- Resolves #
> Fix French translations

- .github/workflows/bump-version.yml
- .github/workflows/prepare-version-bump.yml
- package.json
- Resolves #
See https://github.com/seriouslysean/demo--auto-bump-forked-prs/pull/24/files for an explanation.
> Feature: Automatic release based on version bump

- .github/workflows/prepare-version-bump.yml
> Fix version parse logic

- src/stores/game.js
- Resolves #828 
This was a missed variable name change from #701 it should resolve some of the buggy three stuff
> Wrong Variable Names in UpdateGame()

- api/controllers/game/stalemate.js
- src/stores/game.js
- tests/e2e/specs/in-game/gameOver.spec.js
- Resolves #853 
-Added a `lastEvent` object to `stalemate.js`
-Added logic to check for the `lastEvent` inside the `updateGame` function in the game store
-Added test
> Bug: 853 Stalemate bug

- api/controllers/game/seven/jack.js
- Resolves #861 
- Added helper function to jack file
> Bug #861 Card names undefined

- src/routes/stats/StatsView.vue
- Resolves #870 
-Added conditional check during route update
-Updated where loading values were set
> Bug #870 Redundant stats link error

- api/controllers/game/rematch.js
> fix(rematch.js): set usernames correctly in new game name

- src/routes/game/components/GameCard.vue
> Increase border radius of card selection

- docs/setup-development.md
As recommended [here](https://discord.com/channels/833694928684187669/1214588514855948370/1214595969455362128), I've made a few changes when setting up a development environment on an M1 Linux box.
> Minor spelling fixes & re-arranging of some text

- src/routes/game/GameView.vue
-addresses part of #892
Modified a css rule that used a deprecated version of the :deep selector
> Partial fix for #892 - :deep selector

- package-lock.json
- package.json
> feat: vutify upgrade to 3.5.0

- src/App.vue
- src/routes/rules/components/ScuttleSuitOrder.vue
> CSS Fixes for Rules Page

- src/routes/rules/components/RulePreviewDialog.vue
- Resolves #932
Decided to use 90vw as max-width of dialog.
> Fix Issue 932

- src/routes/game/GameView.vue
> Issue 779: Allow spectator to "Go Home" when game dialog is active

- src/translations/es.json
- src/translations/fr.json
- Resolves #907
Also improved some already translated text in spanish. Credits to [kawaljen](https://github.com/kawaljen) for french translation.
> Feature 907: Translate the values still in English in the Spanish and French translation files

- src/stores/game.js
- Resolves #972 
- Created new reusable function
- Refactored old functions to utilize new reusable generic api call function
> Store API Call Refactor

- cypress.config.js
- src/stores/game.js
- tests/e2e/specs/in-game/basicMoves.spec.js
- tests/e2e/support/commands.js
- Resolves #974
Added helper cypress command to re-use code and use dynamic URLs
> DevEx #974 Refactor Cypress Commands

- src/routes/home/components/FiveChangeDialog.vue
- src/translations/en.json
- src/translations/es.json
- src/translations/fr.json
- tests/e2e/specs/in-game/game-over/rematch.spec.js
- tests/e2e/specs/in-game/spectating.spec.js
- tests/e2e/specs/out-of-game/authentication.spec.js
- tests/e2e/specs/out-of-game/home.spec.js
- tests/e2e/specs/out-of-game/lobby.spec.js
- tests/e2e/specs/out-of-game/localization.spec.js
- tests/e2e/specs/out-of-game/navigation.spec.js
- tests/e2e/specs/out-of-game/rules.spec.js
- tests/e2e/specs/out-of-game/stats.spec.js
> Updated FiveChangeDialog 

- src/main.js
- tests/unit/specs/client-config.spec.js
- utils/config-utils.js
> Unit test Devtools Bugfix

- src/routes/rules/data/rulesData.js
- src/translations/en.json
- src/translations/es.json
- src/translations/fr.json
Relevant [issue number](https://github.com/cuttle-cards/cuttle/issues/997)
- Resolves #997 
1. All tests were run locally and passed successfully.
2. Linting and formatting have been checked.
1. This pull request adds an FAQ entry which tries to explains what happens when a 5 is played when you have no other cards in hand in English, Spanish and French languages.
2. Also, added an entry to the list of faqs in `src/routes/rules/data/rulesData.js` by putting the string `emptyHandFive`  in the `faq` array.
3. No new features or logic changes were introduced, so no additional tests were required.
4. The changes should be reviewed for linguistic accuracy.
> added an FAQ entry in the json file

- .github/workflows/test-e2e-gamestate.yml
- Resolves #1010 
Combined the build with cypress run and updated the build command to `npm run build:gamestate`
> Bug#1010 GH Actions Gamestate Fix

- api/helpers/lock-game.js
> fix(lock-game): conditionally populate gamestates based on env

- api/helpers/gamestate/moves/draw/execute.js
- api/helpers/gamestate/moves/points/execute.js
> fix: set phase in execute helpers

- api/policies/hasValidMoveBody.js
> feat(hasValidMoveBody): validate card id is in DeckIds

- src/components/StatsScoringDialog.vue
- src/routes/game/components/dialogs/components/RulesDialog.vue
> vue warning about `max-width` prop type fixed

- api/helpers/gamestate/moves/scuttle/execute.js
- api/helpers/gamestate/moves/scuttle/validate.js
- api/helpers/gamestate/publish-game-state.js
- api/policies/hasValidMoveBody.js
- tests/e2e/specs/in-game/basicMoves.spec.js
- tests/unit/fixtures/gameStates/points.js
- tests/unit/fixtures/gameStates/resolveNine.js
- tests/unit/fixtures/gameStates/resolveThree.js
>  scuttling in gamestate

- api/helpers/gamestate/check-game-state-for-win.js
- api/helpers/gamestate/moves/draw/execute.js
- api/helpers/gamestate/moves/one-off/validate.js
- api/helpers/gamestate/moves/pass/execute.js
- api/helpers/gamestate/moves/pass/validate.js
- api/helpers/gamestate/publish-game-state.js
- api/policies/hasValidMoveBody.js
- tests/e2e/specs/in-game/game-over/winConditions.spec.js
- tests/e2e/specs/in-game/one-offs/5_fives.spec.js
>  Pass in gamestate

- src/routes/home/components/CreateGameDialog.vue
- tests/e2e/specs/out-of-game/home.spec.js
- Resolves #https://github.com/cuttle-cards/cuttle/issues/1036
> Feat #1036 enter lobby after room creation

- api/helpers/game-states/moves/seven-points/validate.js
- src/translations/en.json
- src/translations/es.json
- src/translations/fr.json
- tests/e2e/specs/in-game/one-offs/7_sevens/player_sevens.spec.js
Adds test case for validating illegal scuttles via a seven
N/A
> test(player_sevens.spec): add test to validate illegal scuttles

- src/components/TheUserMenu.vue
- Resolves #1108
- [ yes] Do the tests still pass?
- [ yes] Is the code formatted properly?
>  Add icons to the UserMenu activator

- .github/workflows/prepare-version-bump.yml
- .github/workflows/test-e2e.yml
> feat(.github): bump download-artifact and upload-artifact to v4

- src/translations/en.json
> fix(en.json): fix typo in announcement.paragraph

- api/policies/isLoggedIn.js
- src/stores/game.js
- Resolves [[DevEx]: Rework unauthenticated status codes #1142](https://github.com/cuttle-cards/cuttle/issues/1142)
Alert box popped and showed error "Please login and try again"
Step 1: Logged into Dev Environment by creating account.
Step 2: Open a new browser window and navigate to localhost:8080
Step 3: Logout of account in second window.
Step 4: Try and create a game that requires user to be Auth.
> 1142 rework unauth status codes

- src/i18n.js
- src/translations/de.json
- tests/e2e/specs/out-of-game/localization.spec.js
- Relevant [1150](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- Resolves : German Translation for the website
> Added German to selectable languages (#1150)

- src/stores/game.js
- tests/e2e/specs/in-game/one-offs/5_fives.spec.js
> Bug #1117 Resolve Five Animation

- src/routes/home/components/announcementDialog/data/announcementData.js
> Fix: End date of announcement

- src/routes/home/components/announcementDialog/data/announcementData.js
> Fix: Start Date for Announcement Dialog

- config/policies.js
dear god what have I done
- Resolves #
> fix: apply developmentOrStagingOnly to wipeDatabase

- api/helpers/game-states/create-socket-event.js
> fix(create-socket-event): set pNum on player objects
